name: CI for restaurant

on:
  pull_request:
    branches: [development, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: ci for backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build
          npm test
      - name: ci for frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
          npm run test-ci
      - name: SonarCloud
        working-directory: ./backend
        run: npm test:cov
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
